production:
  repositories:
    quay:
      url: quay.io
      username: _env:QUAY_USERNAME
      password: _env:QUAY_PASSWORD
      email: _env:QUAY_EMAIL
  services:
    web:
      image: khash/simple_web
      command: bundle exec rackup -p 3000
      build_command: bundle exec rake db:create
      deploy_command: bundle exec rake db:migrate
      local_ports:
        - 3000
      public_port: "80:443"
      pre_start_signal: "USR1"
      pre_stop_sequence: "1m:USR2:30s:USR1:50s"
      stop_grace: "30s"
    node:
      image: khash/node
      command: node test.js
      local_ports:
        - 1337
      public_port: "8080"
      requires:
        - "web"
    boom:
      tarball: http://s3.amazonaws.com/docker_images.cloud66.com/ruby_v200p353-.-1.tar.gz
      command: bundle exec rackup -p 3000
      work_dir: /myapp
      local_ports:
        - 3000
      public_port: "8000"
      requires:
        - "web"
        - "node"
  databases:
    - "mysql"
